"""Declared column lists for the datasets this package reads.

Validation used to rediscover the columns of every dataset on every session opening, by
opening each file and reading its header. That is 11 file opens per initialization to learn
something that does not change - and on network storage each open is a round trip, which is the
cost that matters rather than the milliseconds.

So the columns are declared instead, in `dataset_columns.json`, generated by `build.py`.

**Two copies, with a precedence rule.** The one that wins is the *generated* copy inside the
data root (`<data_root>/auxiliar/dataset_columns.json`), refreshed weekly by
`schema.refresh` from the data actually on disk - so the declaration in force is never more
than one cycle behind the ETL. The copy committed next to this module is the fallback, and it
is versioned on purpose: git history is the reviewable record of how the schema changed
between releases. If the generated copy is absent or unparseable - a fresh checkout, a data
root that has not synced, a refresh that never ran - the service falls back to the last
reviewed schema rather than to reading every header again.

**Keyed by client, not shared.** Four of the eleven datasets carry different columns per
client: capstone's `alerts_detail` has 113 columns against CDA's 54, and its `predictive_motor`
has 337 against 128. A single shared list would be wrong for somebody.

**Trusted, with two lines of defence, because "definitive" means "for now".** If a column is
renamed upstream, validation would report a source as valid against a schema that no longer
holds. What catches it:

1. Every query resolves its columns through `_resolve_column`, which returns ``None`` and
   raises a specific error rather than producing a wrong answer. The failure moves from the
   session opening to the moment that column is used - later, but louder.
2. `verify_against_disk` compares the declaration with the real headers once per container, in
   the background, and publishes the result in `/diagnostics`.

And `CAMPBELL_AI_FROZEN_SCHEMA=false` returns to reading headers without deploying code.
"""

from __future__ import annotations

import json
import logging
import os
import threading
import time
from pathlib import Path
from typing import Any, Optional

logger = logging.getLogger("campbell_ai.schema")

# The committed fallback. Lives next to the module so it travels with the image, and is
# versioned on purpose: git history is the reviewable record of how the schema changes
# between releases.
SCHEMA_FILE = Path(__file__).with_name("dataset_columns.json")

# Name of the generated copy inside the data root. It sits beside `manifest.json` because
# it describes that same data: whoever syncs the data can regenerate and drop it here.
GENERATED_SCHEMA_NAME = "dataset_columns.json"
GENERATED_SCHEMA_SUBDIR = "auxiliar"

# How often the candidates are re-stat'ed to notice a regeneration. Not per lookup:
# `declared_columns` is called once per dataset inside `validate_client`, so a stat there
# would put back a fraction of the filesystem round trips the declaration exists to remove.
# The generated copy is refreshed weekly, so a minute of detection lag costs nothing.
_FRESHNESS_INTERVAL_SECONDS = 60.0

_LOCK = threading.Lock()
_LOADED: Optional[dict[str, Any]] = None
_LOAD_ERROR: str = ""
_SOURCE: str = ""
_SOURCE_PATH: str = ""
_GENERATION: tuple = ()
_CHECKED_AT: float = 0.0


def frozen_schema_enabled() -> bool:
    """Whether declared columns may be used instead of reading a header."""
    raw = os.getenv("CAMPBELL_AI_FROZEN_SCHEMA")
    if raw is None:
        return True
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _data_root() -> Path:
    """Where the data lives, resolved exactly as `CampbellSettings` resolves it.

    Read from the environment rather than imported from `config`, because this module is
    imported by `data.py` and a settings object is more than this needs.
    """
    raw = (
        os.getenv("CAMPBELL_AI_SCHEMA_DATA_ROOT")
        or os.getenv("CAMPBELL_AI_DATA_ROOT")
        or str(Path(__file__).resolve().parents[3] / "data")
    )
    return Path(raw).expanduser()


def generated_schema_file() -> Path:
    """The generated copy that takes precedence over the committed one."""
    return _data_root() / GENERATED_SCHEMA_SUBDIR / GENERATED_SCHEMA_NAME


def _candidates() -> list[tuple[str, Path]]:
    """Where to look, in order of precedence.

    The generated copy wins because it is derived from the data actually on disk and is
    regenerated weekly; the committed one is the fallback that guarantees the service always
    has a declaration - a fresh checkout, a data root that has not synced, a refresh that has
    never run. Losing the generated copy therefore degrades to the last reviewed schema, not
    to reading every header again.
    """
    return [("generated", generated_schema_file()), ("packaged", SCHEMA_FILE)]


def _generation() -> tuple:
    """Fingerprint of every candidate, so a regeneration is noticed without parsing."""
    marks: list[tuple] = []
    for name, path in _candidates():
        try:
            stat = path.stat()
            marks.append((name, stat.st_mtime_ns, stat.st_size))
        except OSError:
            marks.append((name, 0, 0))
    return tuple(marks)


def _read_first_usable() -> tuple[dict[str, Any], str, str, str]:
    """First candidate that parses, as (clients, source, path, error).

    The error is reported even when a later candidate succeeded. A broken generated copy that
    fell back to the committed one is a working service *and* something somebody has to fix,
    and reporting only "source: packaged" would leave an operator inferring the difference
    between "the refresh has never run" and "the refresh produced something unreadable".
    """
    errors: list[str] = []
    for name, path in _candidates():
        try:
            document = json.loads(path.read_text(encoding="utf-8"))
            clients = document.get("clients")
            if not isinstance(clients, dict):
                raise ValueError("falta el mapa 'clients'")
            return clients, name, str(path), "; ".join(errors)
        except FileNotFoundError:
            # Absent is the normal state of the generated copy before the first refresh.
            continue
        except Exception as exc:  # noqa: BLE001 - try the fallback, never fail
            errors.append(f"{name}: {type(exc).__name__}: {exc}")
            logger.warning(
                "No se pudo leer la declaracion en %s (%s); se intenta el respaldo",
                path,
                exc,
            )
    return {}, "none", "", "; ".join(errors)


def _load() -> dict[str, Any]:
    """The declaration in force. Parsed once, re-checked at most once a minute.

    A missing or broken file is never fatal: a candidate that will not parse falls through to
    the next one, and no usable candidate degrades to reading headers as before.
    """
    global _LOADED, _LOAD_ERROR, _SOURCE, _SOURCE_PATH, _GENERATION, _CHECKED_AT
    with _LOCK:
        now = time.monotonic()
        if _LOADED is not None and now - _CHECKED_AT < _FRESHNESS_INTERVAL_SECONDS:
            return _LOADED
        generation = _generation()
        _CHECKED_AT = now
        if _LOADED is not None and generation == _GENERATION:
            return _LOADED

        previous_source = _SOURCE
        clients, source, path, error = _read_first_usable()
        _LOADED, _SOURCE, _SOURCE_PATH, _LOAD_ERROR = clients, source, path, error
        _GENERATION = generation
        if not clients:
            logger.warning(
                "Sin declaracion de columnas usable (%s); se leeran las cabeceras como antes",
                error or "no se encontro ningun archivo",
            )
        elif previous_source and previous_source != source:
            # Worth a line: which file is in force decides what the service believes about
            # every dataset, and it changing is not something to discover by inference.
            logger.info("La declaracion de columnas ahora viene de %s (%s)", source, path)
        return _LOADED


def declared_columns(client: str, dataset_key: str, suffix: str) -> Optional[list[str]]:
    """Declared columns for one dataset of one client, or ``None`` to read the header.

    ``suffix`` guards against a format change: a dataset that used to be a CSV and is now a
    parquet is a different file, and its declaration should not be believed until regenerated.
    """
    if not frozen_schema_enabled():
        return None
    entry = _load().get(str(client).strip().lower(), {}).get(dataset_key)
    if not isinstance(entry, dict):
        return None
    if str(entry.get("format", "")).lower() != suffix.lstrip(".").lower():
        return None
    columns = entry.get("columns")
    if not isinstance(columns, list) or not columns:
        return None
    return [str(column) for column in columns]


def describe() -> dict[str, Any]:
    """What the declaration holds, for the diagnostics payload.

    Reports *which* file is in force, not only that one loaded. With two candidates and a
    precedence rule, "the declaration says X" is only actionable alongside where X came from:
    a committed fix that a stale generated copy is shadowing looks identical otherwise.
    """
    clients = _load()
    return {
        "file": _SOURCE_PATH or str(SCHEMA_FILE),
        "source": _SOURCE or "none",
        "generated_file": str(generated_schema_file()),
        "packaged_file": str(SCHEMA_FILE),
        "enabled": frozen_schema_enabled(),
        "loaded": bool(clients),
        "error": _LOAD_ERROR or None,
        "clients": {
            client: sum(len(entry.get("columns", [])) for entry in datasets.values())
            for client, datasets in clients.items()
        },
        "verification": verification_report(),
    }


def verify_against_disk(repository: Any) -> dict[str, Any]:
    """Compare the declaration with the real headers. Returns what disagreed.

    Run once per container, in the background: this reads every header, which is exactly the
    work the declaration exists to avoid on the hot path. Paying it once, off the critical
    path, is what turns a silent divergence into a visible one.
    """
    from src.campbell_ai.data import DATASETS

    checked = 0
    mismatches: list[dict[str, Any]] = []
    for client, datasets in _load().items():
        for spec in DATASETS:
            if spec.key not in datasets:
                continue
            try:
                path = repository.dataset_path(spec.key, client)
            except Exception:
                continue
            if not path.exists():
                # Now that validation assumes presence, this is the one place that actually
                # looks - so an absent dataset has to be reported, not skipped.
                mismatches.append(
                    {"client": client, "dataset": spec.key, "missing_file": str(path)}
                )
                continue
            try:
                real = repository.read_columns(path)
            except Exception as exc:  # noqa: BLE001 - a failed read is not a mismatch
                mismatches.append(
                    {"client": client, "dataset": spec.key, "error": f"{type(exc).__name__}: {exc}"}
                )
                continue
            checked += 1
            expected = [str(c) for c in datasets[spec.key].get("columns", [])]
            if real != expected:
                missing = [c for c in expected if c not in real]
                added = [c for c in real if c not in expected]
                mismatches.append(
                    {
                        "client": client,
                        "dataset": spec.key,
                        "declared": len(expected),
                        "real": len(real),
                        # Truncated: the point is to notice, not to print a schema.
                        "missing": missing[:10],
                        "added": added[:10],
                    }
                )
    report = {"checked": checked, "mismatches": mismatches}
    if mismatches:
        logger.warning(
            "El esquema declarado no coincide con los datos en %s casos: %s",
            len(mismatches),
            [f"{m.get('client')}/{m.get('dataset')}" for m in mismatches],
        )
    else:
        logger.info("Esquema declarado verificado contra %s datasets, sin diferencias", checked)
    return report


# Result of the last verification, for `/diagnostics`. A divergence between the declared
# schema and the data is exactly the failure mode the declaration introduces, so it has to be
# visible somewhere an operator looks - not only in a log line that may have rotated away.
_VERIFICATION: dict[str, Any] = {"state": "pending"}
_VERIFIER: Optional[threading.Thread] = None
_STOP = threading.Event()

def stop_schema_verification() -> None:
    """Stop the background pass so a container shutdown is not waiting on it."""
    _STOP.set()


def verification_report() -> dict[str, Any]:
    """What the last schema verification found."""
    return dict(_VERIFICATION)


def start_schema_verification(repository: Any) -> bool:
    """Verify the declaration against disk once, in the background. True if started.

    In a thread and not awaited: it reads every header, which is the work the declaration
    exists to avoid on the hot path. Paying it once per container, off the critical path, is
    what keeps a silent divergence from staying silent.
    """
    global _VERIFIER
    if not frozen_schema_enabled():
        _VERIFICATION.update({"state": "disabled"})
        return False
    if _VERIFIER is not None and _VERIFIER.is_alive():
        return False

    def run() -> None:
        try:
            report = verify_against_disk(repository)
            _VERIFICATION.clear()
            _VERIFICATION.update({"state": "verified", **report})
        except Exception as exc:  # noqa: BLE001 - a failed check must not kill the process
            _VERIFICATION.clear()
            _VERIFICATION.update({"state": "error", "error": f"{type(exc).__name__}: {exc}"})
            logger.warning("La verificacion del esquema declarado fallo", exc_info=True)

    _VERIFIER = threading.Thread(target=run, name="campbell-schema-verify", daemon=True)
    _VERIFIER.start()
    return True


def reset() -> None:
    """Forget the loaded declaration. For tests."""
    global _LOADED, _LOAD_ERROR, _SOURCE, _SOURCE_PATH, _GENERATION, _CHECKED_AT
    with _LOCK:
        _LOADED = None
        _LOAD_ERROR = ""
        _SOURCE = ""
        _SOURCE_PATH = ""
        _GENERATION = ()
        _CHECKED_AT = 0.0
    _VERIFICATION.clear()
    _VERIFICATION.update({"state": "pending"})
